### ISSUE TITLE
Невозможно зашифровать при пустом A

### ISSUE THREAD

**Issue by krisk0** [bmstu-iu9/practice-2020-kuznechik#2]
Согласно разделу 5.1 документа Р_1323565.1.026-2019 длина дополнительных имитозащищаемых данных A может быть нулевой.

При пустом A функция mgm_128_finalize возвращает -2.

Прошу убрать проверку длины A в mgm_128_finalize: вместо
```
if (ctx->associatedSize == 0 || ctx->dataSize == 0) {
```
написать 
```
if (ctx->dataSize == 0) {
```
или вообще убрать этот оператор if

**Comment by Mazdaywik** [comment]
@Roninsc2, поправьте, пожалуйста, если замечание верно.

Я кинул Вам приглашение в @bmstu-iu9, чтобы Вы могли получить доступ к репозиторию. Или сделайте форк + пулл реквест.

**Comment by Mazdaywik** [comment]
Исправлено в https://github.com/bmstu-iu9/practice-2020-kuznechik/commit/6084b353f77bfb046137839f122d32ea650d3b95.
